mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.blackmagicwoman.mybatistest.entity  # 注意：对应实体类的路径
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  #main:
  #  allow-circular-references: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  pattern:
    console: "%d - %msg%n"
  level:
    com.blackmagicwoman.mybatistest.mapper : info
